### ISSUE TITLE
Quoting config ignored

### ISSUE THREAD

**Issue by djamadeus** [exasol/dbt-exasol#72]
The quoting options in source-configuration as well as overwriting values in table-config are being ignored.

```
sources:
  - name: TEST
    quoting:
      database: true
      schema: true
      identifier: true
    schema: TEST
    tables:
      - name: order
        identifier: order
        quoting:
          identifier: true
```
The following query gets generated:

`Select "id" as original_order_id  from TEST.order`
